[package]
name = "advent-of-code-2022-day-02"
version = "0.1.0"
authors = ["Rahul Ahuja"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
itertools = "*"
